//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenshotProMax.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageGUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenshotProMax.Resources.LanguageGUI", typeof(LanguageGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string SettFlyLang {
            get {
                return ResourceManager.GetString("SettFlyLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string SettFlyStyle {
            get {
                return ResourceManager.GetString("SettFlyStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptfarbe.
        /// </summary>
        public static string SettFlyMainCol {
            get {
                return ResourceManager.GetString("SettFlyMainCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzentfarbe.
        /// </summary>
        public static string SettFlyActCol {
            get {
                return ResourceManager.GetString("SettFlyActCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Informationen.
        /// </summary>
        public static string SettFlyAppDetailInfo {
            get {
                return ResourceManager.GetString("SettFlyAppDetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string SettFlyAppSettings {
            get {
                return ResourceManager.GetString("SettFlyAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuen Bug oder Feature-Request melden.
        /// </summary>
        public static string TtNewBugOrFeatureCommand {
            get {
                return ResourceManager.GetString("TtNewBugOrFeatureCommand", resourceCulture);
            }
        }
    }
}
